syntax = "proto3";

import "google/protobuf/empty.proto";
import "auth/user_credentials.proto";
import "auth/token_pair.proto";
import "auth/refresh_request.proto";
import "auth/change_password_request.proto";
import "auth/register_request.proto";

package auth;

option java_multiple_files = true;
option java_package = "org.example.ai_auth_service.proto.auth";
option go_package = "github.com/Jewish-Baikal-Autonomy-Territory/auth-service/internal/api/grpc/auth";

service Auth {
  rpc Login(UserCredentials) returns (TokenPair) {}
  rpc Register(RegisterRequest) returns (google.protobuf.Empty) {}
  rpc Refresh(RefreshRequest) returns (TokenPair) {}
  rpc ChangePassword(ChangePasswordRequest) returns (google.protobuf.Empty) {}
}