syntax = "proto3";

import "google/api/field_behavior.proto";

package auth;

option java_multiple_files = true;
option java_package = "org.example.ai_auth_service.proto.auth";
option go_package = "github.com/Jewish-Baikal-Autonomy-Territory/auth-service/internal/api/grpc/auth";

message ChangePasswordRequest {
  string old_password = 1 [
    json_name = "old_password",
    (google.api.field_behavior) = REQUIRED
  ];

  string new_password = 2 [
    json_name = "new_password",
    (google.api.field_behavior) = REQUIRED
  ];
}